print("Hello MY Gang")
name = input("enter your name: ")
print("You are a superhero",name)
print("whats yours Age")
age = input("enter your age:")
print("so you are a little fellow",age)
print("where do you live ..?")
city = input("enter your city:")
print("i AM gonna come there and gonnna kill you IN YOUR CITY",city)
print("Game Over")